server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JaviElMago/Config.git

            username: ${GIT_USER}
            password: ${GIT_PASS}

  security:
    user:
      name: root
      password: secret